on:
  push:
    branches:
    - development
    - release
  pull_request:
    branches:
    - release

jobs:
  build-and-test:
    name: Checkout the latest release code, build it and test it
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout 
        uses: actions/checkout@v3.3.0
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Run all tests
        run: dotnet test --configuration Release

  
